// PlanetSimulation: physical models, numerical choices, and alternatives.
// From repository root: typst compile --root . docs/journal/paper.typ docs/journal/paper.pdf
#let navy = rgb("#17334b")
#let teal = rgb("#177f89")
#let grey = rgb("#647889")
#let pale = rgb("#f2f7f8")
#set page(paper: "a4", margin: (x: 2.0cm, y: 1.8cm), footer: context [#align(center)[#counter(page).display()]])
#set text(font: "New Computer Modern", size: 10pt)
#set par(justify: true, leading: 0.6em)
#set heading(numbering: "1.")
#show heading: set text(fill: navy)
#show figure.caption: set text(size: 8.4pt, fill: grey)

#align(center)[
  #v(0.6cm)
  #text(size: 25pt, weight: "bold", fill: navy)[Physics of a Planetary Renderer]
  #v(0.25cm)
  #text(size: 14pt, fill: teal)[Models, approximations, and alternative approaches in PlanetSimulation]
  #v(0.25cm)
  #text(size: 9.5pt, fill: grey)[Implementation study · version 0.0.1]
]
#v(0.65cm)
#block(fill: pale, radius: 7pt, inset: 14pt)[
  *Abstract.* PlanetSimulation couples terrain, prescribed orbital motion, reflected illumination, and an optically active atmosphere in an interactive renderer. This paper explains the physical ideas behind those models and the approximations that make them practical. Particular attention goes to atmospheric density, molecular and aerosol extinction, single scattering, twilight visibility, and refractive ray curvature. For each major subsystem, we compare the implemented method with a plausible alternative and state what physical behavior is retained or lost. Twelve generated vector diagrams explain the algorithms; versioned captures show actual rendering. The reported GPU benchmark comes from the project README and is qualified by its original workload and hardware. The model is intentionally limited: it does not solve climate, fluid flow, multiple atmospheric scattering, or mutual N-body gravity.
]
#v(0.3cm)
*Keywords:* real-time graphics · procedural terrain · Keplerian dynamics · atmospheric optics · adaptive rendering · reproducible engineering

= Scope and physical questions

The paper describes the current source and its reproducible images, not a claim of physical fidelity for every planet. The useful questions are causal: what determines a surface point, what gravitational model moves the bodies, what radiance reaches the eye, and which terms can be approximated without destroying the intended visual behavior? Equations are simplified descriptions of the implementation; where a coefficient is tuned for the miniature scene, that is stated explicitly. Images come from `docs/screenshots/`, with capture inputs and hashes in `docs/captures/generation.json`. Diagrams in `figures/` are explanatory schematics generated by `make_figures.py`.

The atmosphere deserves special care. A convincing sunset depends on the length and density of the optical path, not merely on a sky color. The renderer therefore keeps absorption, out-scattering, in-scattering, and geometric visibility as separate quantities. Its reference pressure and temperature are configured inputs; no weather or climate equation evolves them. Tests and controlled captures check specific invariants and regressions, but an attractive image alone cannot establish that the numerical model is physically accurate.

= Representing a planet in a camera

== From configuration to a projected sphere

A position in a planet's local mesh is transformed by a model matrix, a camera view matrix, and a projection matrix. In the project's column-vector convention,

$ x_"clip" = P V M x_"local", quad x_"ndc" = x_"clip" / w_"clip" . $

This mapping establishes which physical coordinates each calculation uses. Heights belong to the rotating planet frame; orbital positions and light directions belong to the world frame; depth and pixel reconstruction belong to the camera frame. Mixing them can make a mountain move under a stationary observer or make a shadow follow the camera. GLM supplies the matrix operations, while behavior tests check the resulting projections. @fig:transform records the data path.

#figure(image("figures/early/transforms.svg", width: 100%), caption: [The foundational transform and shading path. `P V M` follows the current shader convention; the final display transform happens after linear-light composition. Generated schematic.]) <fig:transform>

A hidden-window `--render-test` and PNG smoke test make camera framing, framebuffer readback, and image output observable in headless environments. @fig:solar is an actual capture of a compact regression scene. It is evidence of the current renderer at a fixed input state.

#figure(image("../screenshots/solar-view.png", width: 82%), caption: [Headless rendering of the compact scenario. It checks the projected positions of the bodies at a reproducible input state. Source: `docs/screenshots/solar-view.png`; provenance: `docs/captures/generation.json`.]) <fig:solar>

== A reproducible scene as an experimental unit

The JSON parser performs type and range checks before GPU resources are replaced. Scene replay stores a resolved scenario, camera, time, and quality choices next to a PNG. The image is an observation; its sidecar specifies a repeatable input state. On live reload, a new CPU scene is staged before the current one is exchanged, so an invalid or half-written file retains the last valid scene. This matters for physical comparison: changing the camera or exposure at the same time as atmospheric density would confound the result.

= Terrain as a sampled physical surface

== Procedural surface as a camera-independent function

The surface height is evaluated in a normalized planet-local radial direction $u$. A simplified form is

$ h(u) = h_"landscape"(u) + sum_i A_i f_i(u; "seed"_i, "frequency"_i, "octaves"_i). $

The implemented functions include value-noise fBm and a ridged variant. Broad continent and cliff fields determine large-scale shape; finer octaves add local detail. This is synthetic topography: it has spatial correlation and multiple length scales but no tectonics, erosion, or material transport. The seed and local coordinate frame make repeated samples of the same point deterministic. Since terrain geometry is rebuilt as the camera moves, a view-dependent height function would make the ground itself rise and fall. The current code samples `heightAt(radial)` during every LOD rebuild. @fig:terrain distinguishes the fixed field from its variable triangulation.

#figure(image("figures/early/terrain.svg", width: 100%), caption: [The height field is fixed in planet coordinates; eight distance levels change density and apply a bounded inward offset to coarser regions. Bars show the working segment anchors and interpolated levels; the sphere is schematic. Generated schematic.]) <fig:terrain>

The sphere begins with 20 icosahedral faces, subdivided twice into 320 stable base faces. For nearby views, each base face is assigned one of eight edge-segment levels using its angular distance to the eye. A previous-zone hysteresis margin prevents repeated switching at a threshold. Steep faces can receive extra segments if the triangle budget permits. Edges shared by unequal zones are sampled once at the finer requirement, then reused on both sides; concentric interior rings fill the faces without T-junctions. The budget loop first removes optional steep refinement and then lowers less-important zones. This preserves one continuous sampled surface under a per-planet triangle ceiling.

The working segment sequence, from coarse to fine, is 3, 5, 6, 8, 10, 12, 14, 16. Existing base, middle and maximum settings anchor levels 0, 3 and 7. Seven surface-distance boundaries span 300 to 1000 m. The three-zone counts in older reports remain an aggregate (level 0, levels 1–6, level 7); captures now also print all eight counts.

Coarse samples receive an inward displacement $s = s_"max" ((n_"max" - n) / (n_"max" - n_"base"))^2$, clamped to zero for extra-steep detail. The configured `sink_depth_m` defaults to 1 m, additionally bounded to 0.1% of the radius remaining after maximum relief. Shared corners use the smallest incident offset; edges use the finer neighbor, with smooth interpolation toward corners and face centers. Shore refinement carries this scalar field through subdivision before displacement is applied. There is exactly one selected surface per direction, so coarse shells cannot poke through a simultaneously rendered fine shell. The sea uses the same eight-level selection with zero sinking. Geometry, shadows, reflections and foliage roots agree on the installed mesh.

This is a spatial sinking rule, not an animated LOD crossfade. Hysteresis and stable choices preserve vertices within unchanged levels; crossing a level can still move geometry. An offset below the sampled height also does not establish an error bound everywhere inside a triangle on arbitrary procedural relief. The accompanying `benchmarks/terrain-lod.md` records tests and controlled captures.

Two fixed before/after views (shoreline and grass) use all eight levels. Each already reaches the 100,000-triangle land budget and 60,000-triangle water budget, so this change redistributes detail rather than reducing those totals. Land uploads remain 12,000,000 bytes per rebuild; the sink scalar adds CPU metadata but no GPU vertex attribute or draw. The shoreline retains 19 finest base faces and the grass view retains 18. Capture timings overlapped compilation and are not used as performance evidence. Replay inputs, image pairs, logs and hashes are retained under `benchmarks/terrain-lod/`.

An alternative is a cube-sphere quadtree with screen-space error bounds. It can allocate triangles more directly to projected error and support very large planets, but needs explicit seam and level-transition rules. A fixed high-resolution sphere avoids LOD transitions at the cost of drawing distant detail that cannot affect the image. Here the icosahedral base and fixed height query suit a small interactive scene where local walking must remain stable.

The sampled height feeds normals and terrain color factors as well as eye clearance. Water is a separate spherical shell, an approximation that omits tides and waves in the body's shape. The local camera follows the planet's translation and rotation through a planet-fixed frame, so the same latitude/longitude refers to the same terrain location after orbital motion or spin. Walking near a pole uses a great-circle step and parallel transport of the view basis; longitude itself becomes singular there. @fig:pole illustrates why transporting the basis in 3-D is better behaved than rebuilding it from longitude after every step.

#figure(image("figures/early/pole.svg", width: 100%), caption: [Great-circle position update and basis transport across the north pole. A longitude-derived frame can flip at the pole; a transported 3-D basis remains continuous. Generated schematic.]) <fig:pole>

#figure(image("../screenshots/surface-view.png", width: 83%), caption: [Surface-camera capture of procedurally generated terrain. Geometry derives from the stable height function while tessellation is selected for this camera. Source: current gallery.]) <fig:surface>

= Orbital motion and light transport

== Prescribed Kepler ellipses with collective mass

A body names its parent and supplies semi-major and semi-minor axes $a,b$, a mean anomaly, inclination, ascending node, and periapsis orientation. The two-body approximation gives eccentricity and period as

$ e = sqrt(1 - b^2 / a^2), quad mu = G (m_"parent" + m_"collective"), quad T = 2 pi sqrt(a^3 / mu). $

Here $a$ and $b$ are converted from the scenario's distance unit to metres before applying the SI gravitational constant; the code performs the equivalent calculation in world units. At time $t$, mean anomaly advances linearly, representing equal areas swept in equal times. A bounded bracketing solve obtains eccentric anomaly $E$ from $M = E - e sin E$, and the orbital-plane position is $(a(cos E-e), b sin E)$. Three rotations orient that ellipse in the world. The implementation uses a rationalized form near extreme periapsis to avoid cancellation. Evaluating at absolute time avoids frame-rate-dependent drift and makes pausing, replay, and speed changes deterministic.

#figure(image("figures/dynamics/kepler.svg", width: 100%), caption: [An ellipse is specified relative to a focus; a child subtree and its parent recoil around a mass-weighted center. The right panel abstracts the Earth–Moon relation; sizes and offsets are not to scale. Generated schematic.]) <fig:kepler>

Each subtree acts as a collective point mass in its parent's prescribed ellipse; children induce mass-weighted recoil of the parent. Thus an Earth–Moon pair has an internal barycenter, and the Sun moves in response to its descendants while its configured position remains the time-zero anchor. This retains the main geometric and mass-weighted effects while omitting inter-branch perturbations and tidal evolution. A symplectic N-body integrator would capture mutual perturbations and long-term exchange of energy and angular momentum, but would need initial velocities, a suitable time step, and careful treatment of close encounters. Prescribed ellipses are a good fit for deterministic scene replay, not for predicting orbital evolution.

For the `O` overlay, the application samples the complete hierarchy at 321 times for each body: ten revolutions at 32 segments per revolution. A moon's inertial trail must inherit its parent's translation rather than drawing one stationary local ellipse. @fig:trails shows that distinction.

#figure(image("figures/dynamics/orbit-trails.svg", width: 100%), caption: [Illustrative moon trail in the inertial world frame. The repeated local cycles travel with the parent; the curve is explanatory and does not plot a measured scenario trajectory. Generated schematic.]) <fig:trails>

== Light transport before atmospheric composition

Per-frame CPU lighting computes direct flux with inverse-square distance and reflected flux with geometric albedo, a diffuse-sphere phase function, and inverse-square reflector-to-receiver falloff. Sun luminosity is derived from absolute bolometric magnitude using the IAU zero point. The phase law matters: a full moon presents more of its illuminated hemisphere to the receiver than a crescent. Shaders sum direct, reflected, and indirect contributions in linear RGB before an exponential display shoulder and sRGB encoding. Summing encoded display values would break the proportional meaning of flux and exposure.

A directional orthographic depth map is made per planet from the local Sun direction. The same map constrains opaque terrain, water, and direct atmospheric scattering. Its depth test approximates geometric occlusion by terrain; it does not solve light diffraction or soft penumbrae from the full solar disk. The map is cached until local Sun direction, terrain revision, extent, or resolution changes enough to alter its result. Ray tracing each point toward the Sun would give a more direct visibility test and potentially better soft shadows, but its cost is high for every surface fragment and atmospheric sample. @fig:lighting separates the direct and reflected paths.

#figure(image("figures/dynamics/lighting.svg", width: 100%), caption: [The Sun contributes direct flux to each body, the Moon reflects a phase-dependent portion toward the planet, and terrain visibility controls direct light. The diagram is schematic; arrow widths do not encode flux.]) <fig:lighting>

#figure(grid(columns: (1fr, 1fr), gutter: 8pt,
  image("../screenshots/moonlit-night.png", width: 100%),
  image("../screenshots/moonless-night.png", width: 100%)),
  caption: [A controlled night-scene comparison from the current gallery: moonlit (left) and moonless (right). The saved replays preserve camera and lighting inputs, allowing the reflected-light term to be isolated.]) <fig:moonlight>

= Atmospheric optics: from air state to pixel radiance

== Why density is modeled as a vertical profile

In an approximately isothermal atmosphere under roughly constant gravity, hydrostatic balance and the ideal gas law produce an exponential molecular density with scale height $H approx k_B T / (m g)$ (R6). PlanetSimulation uses the same shape for molecules and a separate, usually shorter shape for aerosols:

$ rho_"m"(h) = exp(-h/H_"m"), quad rho_"a"(h) = exp(-h/H_"a") . $

This is a physically motivated shape, but the actual scale heights are set to fractions of the configured shell thickness, not calculated from local gravity and temperature. That choice keeps the visible atmosphere proportionate to a small rendered planet. Both densities taper smoothly to zero over the outer 15% of the shell so the finite numerical boundary does not appear as a hard optical edge. A hydrostatic solver with altitude-dependent temperature would produce more defensible densities, especially for a very deep atmosphere; it would also need gravity, thermal state, and boundary conditions that the current scene format does not supply.

At the reference surface, pressure and temperature scale molecular density approximately as $P/T$. Gas mixture changes the reference refractivity and Rayleigh strength. The code samples Rayleigh coefficients at three representative visible wavelengths and rescales their reference column from an 8 km Earth-like value into units of planet radii. This preserves recognizable color separation, including stronger short-wave scattering, but is not a spectral atmosphere prediction for an arbitrary small world. A spectral solver would resolve wavelength-dependent gas and aerosol properties more faithfully, then integrate to display RGB; it would require more storage and sampling per pixel.

== Extinction, scattering, and the color of the sky

Molecular scattering, aerosol scattering, and aerosol absorption enter different terms. For a path of length $s$, optical depth and direct transmittance have the Beer–Lambert form

$ tau(s) = integral_0^s beta_"ext"(l) dif l, quad T(s) = exp(-tau(s)) . $

Here $beta_"ext" = beta_"Rayleigh" rho_"m" + (beta_"aerosol-scatter" + beta_"aerosol-absorb") rho_"a"$, evaluated per RGB channel. Extinction removes light from the original scene color; only the scattering coefficients contribute light into the view. In particular, treating all dust extinction as scattering would make a dense absorbing dust layer too bright. The renderer's red-dust coefficients and droplet approximation are artistic optical parameters, while the molecular wavelength trend follows the Rayleigh idea.

The pixel combines attenuated scene radiance and light scattered into the view:

$ L_"eye" = T_"view" L_"scene" + L_"in" . $

At each view-ray sample, incoming solar radiance is reduced by transmittance along the light path. The source is multiplied by local density and a phase function: Rayleigh scattering uses a symmetric $1 + cos^2 theta$ dependence, while aerosols use a forward-peaked Henyey–Greenstein form with fixed asymmetry $g = 0.65$. The source is then attenuated along the remaining view path before reaching the eye and contributes to $L_"in"$. This is why a long low-Sun path can redden transmitted light while a nearby sky region gains blue molecular scattering. A small indirect fill term approximates light arriving from other directions; it is not a multiple-scattering solve.

The aerosol state responds to configured dust and water. The water partial pressure is compared with a temperature-dependent saturation estimate; excess vapor can become suspended liquid according to a configurable fraction. A simple droplet cross-section gives an extinction estimate from liquid mass and droplet radius. Thus cooling at fixed water input can increase cloud or mist opacity in the model. It does not simulate nucleation, droplet-size distributions, precipitation, or convective transport. A weather model could supply local pressure, temperature, humidity, and liquid water to the optical layer; the current renderer consumes one configured reference state.

Terrain and the planet also control which sample receives direct Sun light. A spherical horizon test blocks the central solar ray below the horizon; a finite solar angular radius softens the twilight transition. Away from that narrow horizon region, the terrain shadow map can block sunlight from a sample near a mountain. The finite-disk transition is an approximation rather than an integration over the Sun's actual disk, and shadow-map resolution limits the detail of mountain silhouettes. Without the terrain query, shadowed air would continue to glow as if its light path passed through a mountain.

The implementation uses bounded midpoint samples for the view integral. Within a sample it integrates constant source and extinction analytically through $(1 - exp(-beta_"ext" d s)) / beta_"ext"$, avoiding an excessive bright contribution in thick dust. A precomputed multiple-scattering atmosphere, such as the approach in R2, would describe high-order skylight and horizon brightening more faithfully. It would require larger lookup tables and careful parameterization when pressure, temperature, dust, water, or geometry change interactively. The present single-scattering calculation keeps those controls responsive and its cost bounded.

== Why refractive rays bend

The same pressure, temperature, and gas composition produce an approximate surface refractive index. At fixed pressure, cooler air is denser, increasing $n - 1$ in this model. The radial profile decreases with altitude and tapers to $n = 1$ at the shell boundary. Fermat's principle says a ray follows a path of stationary optical length; in a smoothly varying index, its direction changes according to the perpendicular component of the index gradient:

$ (d vec(d)) / (d s) = (nabla n - vec(d) (vec(d) · nabla n)) / n. $

Only the gradient perpendicular to the ray bends it; a gradient along the ray changes optical travel time but not direction. A midpoint step follows this curvature, and the radial symmetry gives a useful check: the spherical Snell quantity $n r sin theta$ should remain approximately constant. CPU tests check this invariant and ray reciprocity; GPU tests compare reprojected sky displacement with the CPU reference and check cold-versus-warm configured scenes. @fig:refraction separates ray geometry from scattered radiance.

#figure(image("figures/atmosphere/refraction.svg", width: 82%), caption: [A refractive view ray bends through denser air while solar light contributes scattered radiance. Near terrain keeps its rasterized silhouette; only visible distant imagery is reprojected. Generated schematic.]) <fig:refraction>

The renderer bends a view ray and reprojects a visible distant image pixel when that ray escapes the shell. Near terrain retains its rasterized silhouette, and direct-light shadow rays remain straight. An off-screen or hidden source cannot be reconstructed from the existing color buffer; trapped rays do not leak background light. Full curved-ray tracing through scene geometry would represent refracted terrain and solar visibility more consistently, but would require a different visibility structure and substantially more ray queries. The pressure and temperature dependence has a physical basis (R3), while the chosen constants and miniature-world scale remain a rendering model rather than precision terrestrial refractometry.

A deliberately extreme test compresses the shell to 15 m around the 1 km planet, sets pressure to 150,000 Pa and temperature to 180 K, and places the surface camera 2 m above the ground with a 15-degree field of view. The two actual renderer captures below differ only in the JSON `refraction_enabled` switch. Refraction extends the visible solar limb into sky pixels near the horizon, while the already rasterized Sun and terrain keep their silhouettes. A small pointed edge remains where terrain hides the source image; this is a limit of image reprojection rather than a prediction of solar optics. The setting illustrates the rendering model's behavior, not Earth's atmosphere. The replay sidecars in `docs/captures/replay` preserve the exact resolved scenes.

#figure(grid(columns: (1fr, 1fr), gutter: 7pt,
  image("../screenshots/refraction-extreme-on.png", width: 100%),
  image("../screenshots/refraction-extreme-off.png", width: 100%)),
  caption: [Matched full-resolution renderer captures of extreme refraction enabled (left) and disabled (right). Only the JSON bending switch changes; scattering and exposure remain active in both.]) <fig:extreme-refraction>

#figure(grid(columns: (1fr, 1fr), gutter: 7pt,
  image("../screenshots/atmosphere-day.png", width: 100%),
  image("../screenshots/atmosphere-sunset.png", width: 100%),
  image("../screenshots/atmosphere-mist.png", width: 100%),
  image("../screenshots/atmosphere-dust.png", width: 100%)),
  caption: [Current controlled atmospheric scenarios, left to right and top to bottom: standard air, sunset, condensed mist, and heavy red dust. All four are actual renderer captures from the regression gallery.]) <fig:atmosphere-gallery>

== Where the atmospheric computation is spent

For each visible pixel, the view ray needs repeated density and light-path evaluations. A reusable GPU density-column table stores the geometric integrals of molecular and aerosol density along straight light paths. Since the table stores columns rather than color, changing the gas mixture or dust coefficients can reuse the same geometry and apply new extinction coefficients. Camera motion also leaves the shell geometry unchanged. The main atmosphere field normally uses quarter resolution; a depth-aware resolve reconstructs smooth regions and reintegrates full-resolution pixels near discontinuities. Terrain, stars, and the Sun stay at full resolution. This matches the physical structure of the calculation: smooth optical fields tolerate coarse sampling, while silhouettes and depth edges do not. @fig:atmos-pipeline summarizes the pipeline.

An alternative is full-resolution ray integration for every pixel. It avoids resolve artifacts, but repeats nearly identical work across neighboring sky pixels. A larger multidimensional lookup could reduce per-pixel work further, but would be harder to update for changing aerosol and humidity states. The current split keeps the expensive geometric column reusable while leaving composition as a live control.

#figure(image("figures/atmosphere/pipeline.svg", width: 100%), caption: [Atmospheric rendering graph. A reusable density-column lookup and a reduced scattering field lower repeated work; full-resolution depth controls edge reconstruction. Generated schematic.]) <fig:atmos-pipeline>

The project's recorded Quadro M1000M benchmark at 1280×720 reported 208 ms mean frame time for the original full-field method, 138 ms with the column lookup, and 26 ms with reduced fields and shared ray calculations. These were 90-frame measurements of one surface scene with Debug CPU builds, recorded in the README; @fig:perf reproduces them rather than claiming a new experiment. The approximately eightfold change is specific to that workload and GPU. A separate RelWithDebInfo run reported 28.5 ms. A headless software-rendered capture is not comparable to this hardware benchmark.

#figure(image("figures/atmosphere/performance.svg", width: 100%), caption: [Reported mean frame times from `README.md`, Quadro M1000M, 1280×720, 90 frames. These bars visualize previously reported measurements, not a new benchmark.]) <fig:perf>

A profiler now records CPU stage times and asynchronous GPU timestamp results without blocking for each query. CPU frame time, GPU pass time, and swap/presentation delay answer different questions; adding CPU and GPU times would double-count overlap. A completed HDR scene may be reused if camera, time, viewport, geometry, and pending-terrain state match. The HUD remains separately drawn so input can reveal or hide it immediately.

== Pale sand with centimetre wind ripples

The sand reference requests pale grains and low wind ripples. Beaches now use linear RGB (0.86, 0.83, 0.75), independent of the planet tint, while their fragment-height boundary and grass placement remain unchanged. A body-fixed triplanar wave field has 18 cm spacing, a noise-warped phase and a bounded 7 mm amplitude. Grain at 180 cells per metre adds neutral colour variation, matte roughness and up to 0.7 mm additional height range. Screen derivatives convert this field into normal relief; projection-specific footprint filtering removes unresolved waves and grains. Geometry, depth, collision and shadow silhouettes retain the original mesh. This models the appearance of centimetre dunes rather than transported sand or geometric dune silhouettes.

#figure(image("materials/sand/images/material-patches.png", width: 82%), caption: [Production-shader diagnostic: fine grain across a 16 cm patch under indirect light (left), and wind ripples across a 2 m patch under grazing sunlight (right). Two triangles per patch, with unchanged depth; scales and lighting differ deliberately.]) <fig:sand-material>

GPU checks cover pale colour under a green planet tint, narrow beach boundaries, grain and ripple visibility, distant filtering, rotation, both poles and unchanged depth. The retained shoreline comparison and validation are in `materials/sand.md`. The additional two value-noise samples and three projected waves increase fragment work without increasing geometry or transfers; no hardware timing improvement is claimed.

== Perlin wind on a rotating planet

Grass wind now samples three advected 3D Perlin gradient fields, replacing the earlier overlapping sine waves. The field input is each root in body-local metres, so orbital translation and rotation do not change the local deformation. Gust cells span 12.5 m, direction cells 50 m, and flutter cells approximately 1.4 m. The implementation blends gradient dot products at eight cell corners with the quintic fade $6t^5-15t^4+10t^3$, following the construction in #link("https://cs.nyu.edu/~perlin/noise/")[Ken Perlin's improved-noise reference]. Integer hashing selects corner gradients instead of a permutation table. This is a visual wind model, not a fluid simulation.

The lattice repeats every 256 cells. Drift rates are binary fractions of a cell per second with a common 8192-second period, allowing the double wind clock to wrap before conversion to a float uniform without a discontinuity. Both the main and water-reflection pass use the same field and phase. Wind strength zero leaves the seeded static lean. Live wind follows wall time while T pauses orbits and spin; fixed captures preserve their explicit phase for deterministic replay. The vertex shader adds no textures, triangles or per-instance uploads, but performs more arithmetic than the old sine field. GPU transform-feedback checks exercise lattice and period boundaries, both poles, large wrapped times, fixed blade roots and independence from body transforms; pixel tests retain wind motion, shadowing and reflection clipping checks.

== Historical grass geometry budgets and eight distance levels

These measurements describe the earlier single-triangle/sinking experiment. The current procedural quad implementation below supersedes its geometry, sinking and per-root transfer.

The #link("https://github.com/vercidium-patreon/glvertexid/tree/25f1d1d292eeb9cd50984d933890b1ec00d4c97c")[glvertexid heightmap example] reconstructs regular-grid coordinates from vertex IDs and connects strips with degenerate vertices. Its published example contains neither eight LODs nor sinking; those requested techniques are adapted here to the existing instanced grass. Terrain retains its irregular spherical tessellation and shared shoreline edges, which cannot be represented directly by that regular height-only grid.

Blade strips now terminate in one tip, removing the former duplicate tip vertex and degenerate triangle. Eight nominal distance levels use 6, 5, 4, 3, 2, 1, 1 and 1 segments. At the working 60 m draw range, boundaries are 7.5, 9.375, 11.25, 13.125, 15, 30 and 45 m. Geometry straightens between 3.75 and 7.5 m, before any segment reduction can occur; removing collinear intermediate vertices preserves its shape. The CPU subtracts the 9 m movement allowance when choosing detail, keeping enough geometry while the cached patch follows the walker. Each retained blade submits no more vertices than the previous near/far scheme.

Eight deterministic retention groups thin distant candidates further, retiring one eighth on average in each equally spaced interval from 15 to 60 m. Smooth sinking and collapse update in the shader on every frame. CPU rejection uses the same group hash and adds the movement allowance, so a discarded root cannot become visible before the next rebuild. This deliberately trades distant density and shape detail for less work; the near-camera Gaussian candidates and terrain remain unchanged. Both main and reflection passes use the same decisions. One sorted instance buffer replaces two separate buffers. Compatible one-triangle levels merge into a single draw, leaving at most six instanced draws per pass rather than two previously, but only one instance upload per rebuilt patch.

#table(
  columns: (2fr, 1fr, 1fr), inset: 5pt, stroke: 0.4pt + rgb("#dfe8eb"),
  [*Initial frozen grass view*], [*Previous*], [*Eight LODs*],
  [Uploaded blade instances], [162,828], [146,510],
  [Vertices submitted per pass], [1,477,562], [1,081,766],
  [Triangles submitted per pass], [1,151,906], [788,746],
  [Instance bytes per rebuild], [6,513,120], [5,860,400],
  [Instanced draws per pass], [2], [6],
)

These counts come from the same generated roots: vertex submissions fall by 26.8%, submitted triangles by 31.5%, and instance payload by 10.0%. Triangle counts include submitted degenerates and fully sunk reserved geometry; bytes exclude driver overhead. CPU tests check guard-band visibility and the vertex bound. GPU transform feedback checks endpoint agreement, sinking continuity and distant shape invariance; a primitive query verifies submitted triangle accounting. Full timings, raw traces, executable and shader-tree hashes, frozen inputs and reproduction commands are in `docs/journal/benchmarks/grass-lod.md` and its data directory.

A paired 640×360 walking capture on Mesa llvmpipe with two worker threads measures 20 frames, excluding three warmup frames and the final readback frame. Mean frame time falls from 1576.97 to 1463.22 ms (7.2%); the median falls from 1387.17 to 1295.95 ms (6.6%). The foliage-disabled control changes from 708.99 to 720.05 ms mean, and grass preparation per rebuild remains similar. This single software-renderer pair measures a quality/performance tradeoff, not a hardware FPS guarantee. Both versions rebuild grass six times and install three terrain meshes in the measured window; bare final captures match exactly.

== Procedural grass and terrain-buffer reuse

Grass now swaps between six-segment strips (14 vertices, 12 triangles) and low-detail tapered quads (4 vertices, 2 triangles). A narrow top edge preserves both low triangles. Current camera-to-triangle bounds select geometry without rebuilding roots, while the fragment shader evaluates a shared nonlinear palette so low detail retains the same base-to-tip color. Dithered pixel coverage replaces sinking; grass roots and heights stay fixed while coverage retires. The landscape retains its independent eight-level sinking.

The JSON `quad_distance_m` setting selects the morph endpoint in metres, with morphing starting at half that distance; zero preserves the automatic minimum of 15 m and one quarter of the grass draw distance. CPU draw selection and both shader paths share the threshold independently of root density. Interactive wind follows wall time independently of orbital pause and speed, with whole-frame reuse disabled while wind is animated. Fixed captures retain their explicit wind phase for reproducibility. The native `GrassWindInputIntegration` test waits for the completed surface transition, presses T and the speed keys, verifies changing grass pixels at fixed orbital time, reloads a zero wind speed and requires identical RGB frames. Removing foliage proves that the frozen view contained grass. Resolved scenes, images and traces are retained under `benchmarks/wind/`; see `benchmarks/live-wind.md`.

The quad transition now preserves interior shading by interpolating lateral offset and normalizing by local blade width per fragment. A neutral-light regression reproduced a 13-level RGB difference before the fix. Candidate acceptance uses a stable slot rank with a smooth density-coverage ramp, so crossing a power-of-two batch boundary no longer replaces existing visible roots. Compute/fallback position parity and both transition regressions pass.

#figure(grid(columns: (1fr, 1fr), gutter: 8pt,
  image("benchmarks/wind/images/animated-a.png", width: 100%),
  image("benchmarks/wind/images/animated-b.png", width: 100%)),
  caption: [Native surface frames one second apart with T-paused planetary time. Grass wind continues in the same body-local field; a separate zero-speed comparison is byte-identical. Controlled scene disables water, atmosphere and overlays.])

Grass reuses the terrain's GPU vertex/index buffers through OpenGL 3.3 buffer textures. It uploads only one four-byte triangle ID per selected patch plus small rule uniforms. GLSL generates barycentric roots, blade variation, Gaussian acceptance, biome rejection and Perlin wind. No individual grass positions, blade meshes, random arrays or noise fields are uploaded; cached frames upload zero grass buffer bytes. A bounded CPU plan still reserves candidates and draw ranges. OpenGL 4.3 computes placement and wind once per candidate, compacts visible blades into two GPU queues and issues indirect draws without runtime CPU readback; OpenGL 3.3 retains procedural vertex generation. The separate horizon tuft layer and its controls were removed at the user's request. Ground grass now uses the shared foliage-tip palette at midpoint variation (linear RGB 0.634375, 0.74375, 0.284375). This trades GPU evaluation for lower traffic and does not by itself guarantee higher FPS.

The JSON `foliage.wind_noise` block controls gust, direction and flutter frequencies in cycles per metre, an integer field seed and the wrapped clock's speed multiplier. No sampled wind data crosses the CPU/GPU boundary. Full implementation details and collected validation are in `docs/journal/benchmarks/procedural-grass.md`. A frozen 100,000-candidate view uploads 8,666 four-byte triangle IDs (34,664 bytes), with 12,800,032 bytes of GPU working storage. Its main pass draws 8,678 detailed blades and 2,306 quads. A serial eight-frame, 640 × 360 walking pair on llvmpipe (five retained frames) measures 3125.60 ms mean with vertex generation and 2792.21 ms with compute, a 10.7% reduction; final PNGs match exactly. The main atmosphere pass still costs about 923 ms, and a synchronous capture terrain rebuild costs about 3.3 s. Reflection geometry is slightly slower with compute (208 versus 176 ms). Priorities are atmospheric work, sharing grass evaluation across passes, and terrain tiling or GPU generation: the existing land mesh transfers 12 MB versus 34.7 KB for its grass plan. These are software measurements, not hardware FPS claims.

The live-wind checkpoint subsequently passes all 50 CTest entries in one clean 333.81 s run on the same host. Its native frames change 11,178 RGB channels while 89 completed frames share orbital time 20.2094061 s; zero-speed frames are identical and reload remains paused at 20 s. Evidence is in `benchmarks/wind/validation/`.

== Offline capture: bounded detail without a frame-time target

The `--offline-render` command captures a resolved surface camera at requested native resolution. An independent in-memory profile expands the single grass radius by 1–20 times (20 by default), uses full-resolution atmosphere, raises terrain edge segments to 32 under a 100,000-triangle ceiling, and uses a 256-segment Sun sphere. Other bodies, including a distant Moon, receive a ten-segment base; the camera planet retains its original coarse base to reserve triangles for nearby terrain. Offline sinking is zero. The source scene remains separately stored in the sidecar, so replay applies the profile once. Candidate growth follows area but automatic growth caps at two million (about 256 MB of compute queues); larger explicit scene budgets are retained. Density and biome rejection still apply. This sacrifices a frame-time target while retaining finite memory and tessellation bounds.

A controlled airless capture expands radius from 30 to 600 m and raises submitted Sun triangles from 2,048 to 131,072, Moon triangles from 960 to 86,400, and the camera planet from 9,964 to 99,732. Its 409,600 reserved grass candidates stay within the derived budget; they are not all visible blades. Production transform feedback on compute and vertex paths verifies visible roots beyond the normal cutoff. Actual scene coverage remains conditional on budget, Gaussian density, view and terrain suitability.

A final OpenGL 3.3 pass adds a solar halo, streak and four colored aperture ghosts along the Sun–image-center axis. Synchronous stencil readback measures depth-tested Sun visibility, and visible pixel brightness attenuates the contribution through atmospheric extinction. Fully terrain-hidden Suns contribute zero; partial visibility scales an approximate projected-disk area. The pass adds display-space color after tone mapping and preserves depth/stencil. This is an artistic lens approximation, not spectral lens ray tracing or calibrated diffraction. Its own `lens_flare` trace stage includes the accepted readback cost. Normal/offline on/off captures, zero contribution behind terrain, explicit override checks, invalid replay rejection before window startup and byte-identical self-contained replay are documented in `benchmarks/offline-rendering.md`.

#figure(grid(columns: (1fr, 1fr), gutter: 8pt,
  image("benchmarks/offline/images/normal.png", width: 100%),
  image("benchmarks/offline/images/flare.png", width: 100%)),
  caption: [Controlled airless view: normal radius/detail (left), offline 20× radius with finer bodies and lens flare (right). The Moon partly covers the Sun. Images show a quality profile, not a matched-density performance comparison.])

== Camera movement and grass preparation: measured costs

The following measurements predate the Perlin wind change; their recorded executable hashes and captures identify the earlier sine-wind workload.

On 2026-09-30, a fixed-step benchmark separated the cost of moving the surface camera from orbital motion. Three cases share the same camera and scene: stationary with paused time, walking with grass, and walking without grass. Each capture has 36 frames at 640×360; five warmup frames and the final readback frame are excluded. Walking advances 2 m per frame. The working scene uses a 60 m grass draw distance and a 200,000-blade budget. The host runs Mesa 22.3.6 llvmpipe with two worker threads under Xvfb; CPU code uses GCC 12.2.0 with `-O2`. These are software-renderer measurements, not a reproduction of the reported 30-to-10 FPS change on a physical GPU.

#table(
  columns: (2.0fr, 1fr, 1fr, 1fr),
  inset: 5pt, stroke: 0.4pt + rgb("#dfe8eb"),
  [*Case*], [*Frame mean / median (ms)*], [*GPU passes mean (ms)*], [*Grass per rebuild (ms)*],
  [Before: stationary], [36.64 / 36.59], [2.09], [0],
  [Before: walking], [1089.03 / 872.44], [924.25], [79.92],
  [Before: walking, bare], [620.87 / 478.28], [481.32], [0],
  [After: stationary], [37.26 / 36.96], [2.20], [0],
  [After: walking], [1033.55 / 869.35], [878.71], [50.79],
  [After: walking, bare], [639.14 / 482.17], [498.60], [0],
)

Both walking runs rebuild grass on ten measured frames and install five terrain meshes. All thirty stationary frames reuse the completed scene. Captures construct terrain synchronously for reproducible geometry; live walking already constructs land and water in the background. The optimized capture's CPU mesh stage averages 136.34 ms per frame, with a median near zero. This average must not be interpreted as a render-thread stall in the interactive path. CPU and GPU times overlap, and swap time includes software-driver waits.

Two local changes reduce grass preparation without changing its roots or appearance. A conservative triangle bound rejects candidates whose random sample cannot pass the Gaussian density test, before computing their full geometry. Sorting caches each squared distance once, then sorts compact keys and gathers the instance buffers. Mean placement time on rebuilding frames falls from 55.59 to 35.65 ms, sorting from 23.51 to 14.26 ms, while instance submission stays near 0.85 ms. Complete preparation falls from 79.92 to 50.79 ms, about 36%. Three isolated placement runs per version, alternating order and discarding two warmup iterations per run, reduce median process CPU time from 52.505 to 34.6775 ms (34%). All iterations retain exactly 162,828 blades and identical attribute checksums. All three paired final PNGs are byte-identical.

The median walking frame remains nearly unchanged, at 872 versus 869 ms. Rendering grass, reflected geometry and atmosphere dominates this software-renderer workload. Grass is already instanced and distance-cached; it is drawn in both opaque and reflection passes. Partial patch updates could reduce preparation spikes further, but would not eliminate those draw costs. They also require stable terrain tile identities: candidate seeds currently depend on triangle indices, which can change with tessellation. Reusing roots across mesh revisions without resampling could leave grass above or below the new ground. A future tiled cache or background placement job should retain overlap, rebuild changed tiles and discard obsolete jobs. The later culling and LOD work should measure each render pass on the target GPU before choosing a broader redesign.

Reproduction commands, complete per-pass tables, frozen inputs, raw CSVs, executable hashes and caveats are retained in `docs/journal/benchmarks/camera-movement.md` and its `movement/` data directory. Live traces now expose foliage placement, sorting, upload and rebuild counts separately. No end-to-end hardware FPS improvement is claimed from this single paired software-rendering run.

== Nested CPU tracing and function-level profiling

The optional `--cpu-trace` records nested scopes with elapsed wall time and, where available, calling-thread CPU time. Render and terrain-worker lanes are separate. The standalone HTML report provides expandable caller trees, a chronological SVG timeline, self-time rankings, and reversed callee-to-caller paths. Self time subtracts immediate children; it still includes uninstrumented calls, driver work, waits, and tracing overhead. Inclusive times must not be added across ancestors and descendants. Recording begins in `Renderer::run`, after constructor startup.

A frozen 60 m grass scene was measured on 2026-09-30 with GCC 12.2, Xvfb and two llvmpipe workers, at 640 × 360 pixels. Fourteen frames advance the walking camera by 2 m per frame with simulation time paused; the first three and final frame are excluded. The ten retained walking frames average 4216.18 ms, versus 4179.30 ms with CPU tracing disabled; their final PNGs are byte-identical. This single pair includes host variation and does not establish an overhead bound. Stationary paused-image reuse averages 131.36 ms; walking without grass averages 2021.34 ms. These are software-renderer diagnostics, not hardware FPS measurements.

#table(
  columns: (2.6fr, 1fr, 1fr), inset: 5pt,
  table.header([Scope over ten walking frames], [Wall (ms)], [Thread CPU (ms)]),
  [Grass draws, main + reflection], [16059.27], [16050.88],
  [Atmosphere, main + reflection], [18452.14], [36.81],
  [Terrain construction], [4313.86], [4312.70],
  [Shoreline refinement (inside terrain)], [3683.14], [3682.22],
  [Grass placement], [421.21], [421.17],
  [Grass LOD batching], [150.42], [150.37],
  [Grass upload], [7.99], [7.99],
)

Grass draws consume about 38.1% of scoped frame wall time and 72.1% of the render thread's CPU time, including software OpenGL work. Atmosphere takes 43.8% of frame wall time but little calling-thread CPU time, indicating blocking or scheduling while other driver workers may execute. Terrain construction contributes 10.2%; shoreline refinement is 85.4% of terrain time. Placement, batching and upload together contribute 1.4%, about 145 ms per rebuild. Capture terrain construction is synchronous; the interactive path uses a worker, so capture costs are not interactive render-thread stalls.

The independent Callgrind run records 7,473,993,658 instructions for one terrain build followed by twelve placement/batching iterations, including benchmark checksums. Its exported self and caller/callee reports identify placement, terrain noise, shoreline ordered-map comparisons, rounding and sorting as construction costs. Instruction shares are not time shares; optimized source attribution can split one function across several file entries. This focused CPU workload excludes rendering. Kernel sampling was restricted, and GNU gprofng warned that its interval timer changed; its inconsistent sampled times were rejected. A suitable target-GPU host is still needed for reliable function-level sampled CPU times and hardware optimization conclusions.

#figure(image("benchmarks/cpu/walking/detail/top-down.svg", width: 100%), caption: [Top-down nested CPU scope timeline for three frozen walking frames on llvmpipe. Width represents wall time, including waits.])

#figure(image("benchmarks/cpu/walking/report/bottom-up.svg", width: 100%), caption: [Bottom-up self wall time over ten walking frames. Immediate child scopes are subtracted; uninstrumented work and waits remain.])

The retained study is described in `docs/journal/benchmarks/cpu-profiling.md`. It motivates investigating rendered grass/reflection work, atmosphere execution and shoreline construction before assuming that partial placement updates solve the frame-time problem.

= Visibility, exposure, and interactive constraints

== Diagnostics, dependency boundaries and adaptive quality

The `I`/Tab panel reports timings and optional Linux NVIDIA NVML utilization. Utilization is sampled off the render thread and is device-wide, while GPU pass milliseconds belong to this application's measured passes. Software rendering and ambiguous GPU matching show `N/A`; a fake driver library tests the ABI path without claiming validation on NVIDIA hardware. @fig:overlay is a real captured panel.

#figure(image("../screenshots/performance-overlay.png", width: 83%), caption: [Actual current performance overlay under Xvfb/Mesa llvmpipe. The white-bordered black panel reports FPS, frame time, GPU pass time, and utilization availability; its numbers are capture-environment observations.]) <fig:overlay>

A best-effort 20 FPS quality target uses a smoothed frame estimate $m_t = 0.85 m_(t-1) + 0.15 f_t$ to select one of six scene-resolution scales, from 100% down to 25%. After a 1.5-second cooldown, sustained times above 55 ms lower resolution; times below 32 ms permit recovery. Only moving interactive scenes feed the controller. A graphics-memory estimate can cap the initial scale, reserving most reported memory for other uses; fixed-resolution captures remain deterministic. The HUD stays at native window resolution. @fig:adaptive shows the control law, not a measured response trace. This is a rendering control, not a change to the atmosphere's physical parameters. Its lower resolution may still lose thin clouds or distant silhouettes; a strict 20 FPS guarantee is impossible once the minimum scale is reached or scene cost is unrelated to pixel count.

#figure(image("figures/interaction/adaptive.svg", width: 100%), caption: [Actual controller thresholds and discrete scene scales; bar heights are relative scale, not measured frame rates. Generated schematic.]) <fig:adaptive>

== Visibility must follow the light path

The same visibility principle applies to air and water. A mountain blocks direct sunlight from nearby air, so the direct in-scattering term uses the planet's terrain depth map. The finite solar disk's twilight region remains, as does the approximate indirect fill. For water, a valid bright sample in the reflection image does not prove that a water point is lit: that point may lie on the night side or behind terrain. The direct reflection term therefore requires positive local Sun incidence and terrain visibility. Indirect water radiance remains. @fig:ocean illustrates the distinction. The gallery's terrain-shadow and twilight cases are controlled visual regressions.

#figure(image("figures/dynamics/ocean.svg", width: 100%), caption: [A reflected bright sample can exist in image space even when the water point lies on the night side. Local incidence and shadow-map visibility gate the direct reflection term. Generated schematic.]) <fig:ocean>

#figure(grid(columns: (1fr, 1fr), gutter: 8pt,
  image("../screenshots/terrain-shadows.png", width: 100%),
  image("../screenshots/twilight.png", width: 100%)),
  caption: [Actual current regression captures for terrain shadow visibility (left) and near-horizon twilight (right). Their fixtures and generation commands are recorded with the gallery.]) <fig:shadow-twilight>

== Interpreting motion from the camera

Ten-revolution predictive trails and body cards help distinguish local orbits from inertial paths. The path color averages terrain vertex RGB factors multiplied by the body's configured base tint; labels report name, parent, axes, eccentricity, period, radius, and mass. Sampling the entire orbital system, rather than each child's local ellipse alone, is necessary for moving-parent trails. The overlay is toggled by `O` and hidden in planet and surface cameras; real X11 input tests verify both behaviors.

Orbit-to-surface entry is a one-second wall-clock transition. The starting pose is the last actually rendered view, avoiding a first-frame jump after the key event. An eased parameter $q(u)=3u^2-2u^3$ drives spherical interpolation of the planet-relative radial direction, logarithmic interpolation of radius, quaternion interpolation of orientation, and field-of-view interpolation. Intermediate positions are clamped above sampled terrain and water. The target is resampled while the planet moves, so the transition ends at the current surface pose. This is a camera path rather than physically accelerated descent. The astronaut flight mode separately integrates forces, velocity and collisions. @fig:transition shows the path and ease curve.

#figure(image("figures/interaction/transition.svg", width: 100%), caption: [Orbit-to-surface descent. The curve shows the implemented smoothstep parameter; the spatial path is schematic because the actual start, target, and terrain vary by scene.]) <fig:transition>

= Astronaut locomotion and flight

Camera 4 follows an original procedural astronaut at the same surface location as camera 2. Normal movement is 6 m/s; either Shift key raises it to 12 m/s. The grey and blue suit carries small German upper-arm patches. Body-local grounded contacts follow planet translation and spin, while the grounded chase camera clears the ground and shortens its arm at intervening terrain. Airborne position and velocity use an inertial world frame.

An alternating gait preserves the stance foot and moves only the swinging foot, using a smooth ground-projected trajectory with 15 cm lift. Contacts intersect the installed terrain triangles, including LOD sinking, and resample height after mesh replacement without changing radial location. The MIT-licensed ozz-animation 0.16.0 runtime supplies two-bone leg IK near the actor origin. This combines procedural step selection with a tested joint solver; it is an initial locomotion approximation rather than a motion-captured running cycle. Once walking settles, the pelvis rises over the locked ankles until both knees extend on level ground. The suit and chase view share this adjustment; uneven ground retains the necessary bend. The 0.10 s settling response preserves segment lengths, and exactly straight chains use a collinear midpoint to avoid an IK singularity. Replay includes the body offset; details and the before/after view are in `character/standing.md`.

Space launches at 10 m/s; holding it supplies upward thrust while airborne. A 100 kg actor integrates world-space gravity and quadratic drag relative to moving air, using configured pressure, gas composition and temperature. The suit tilts to direct its single downward exhaust axis, and arms remain quiet while the jetpack is armed. Falling has no artificial velocity cap; drag determines the local terminal speed. Landing resets the flight state. Flight uses full wall-clock elapsed time with 10 ms substeps and interpolated body motion, while grounded walking retains its presentation-time bound. The coasting exhaust axis remains inertial during planet spin.

The production main planet sizes a shared 8.29 kN engine, retained on other planets. At sea level, 100 m/s produces approximately 4.24 kN drag and 424 kW useful horizontal power. Assuming 1,000 m/s exhaust and 60% conversion efficiency, installed maximum thrust corresponds to about 6.91 MW exhaust input. These are explicit idealised choices, not measurements of a real jetpack. Attainable speed depends on gravity, air density and direction on the rapidly spinning miniature planet; the 100 m/s command changes force rather than clipping velocity. The reproducible calculation and limits are in `character/flight.md`. Fuel and thermal limits remain future work.


Airborne WASD now ignites thrust without Space and follows the full camera direction, including look-down descent; Space commands up. Within centre distance 1.2 diameters (2.4 radii), up follows the nearby planet or moon with a 0.35 s response. Beyond all such regions it remains inertial, with unrestricted space-camera pitch. The astronaut can approach the Moon and adopt its frame without teleporting or resetting velocity. Overlapping regions use 10% centre-distance hysteresis. Each flight step sums gravity from the three nearest celestial centres, including the Sun. Atmospheric drag is independent of the orientation switch. Space thrust requests acceleration without the near-body 100 m/s governor. Full details and world-state replay are in `character/space-flight.md`.

#figure(
  grid(columns: (1fr, 1fr, 1fr), gutter: 5pt,
    image("../screenshots/astronaut.png", width: 100%),
    image("../screenshots/astronaut-front.png", width: 100%),
    image("../screenshots/astronaut-jetpack.png", width: 100%)),
  caption: [Actual renderer captures: planted feet and chase view, suit details and arm patch, tilted jetpack thrust and bubbles. Full pose and local effect phase are preserved in the replay sidecars.])

#figure(grid(columns: (1fr, 1fr), gutter: 7pt,
  image("character/space-flight/images/space.png", width: 100%),
  image("character/space-flight/images/moon.png", width: 100%)),
  caption: [Reproducible seeded flight checkpoints: inertial space orientation (left) and entry into the Moon frame (right). These reduced-budget fixtures isolate the actor and omit foliage. Both PNG and complete pose replay exactly; the later settling check measures alignment to Moon up.])

Exhaust markers now emit gradually at 40/s from alternating backpack nozzles, with a 64-particle cap and 1.4 s lifetimes. They inherit astronaut motion, relax toward moving air, expand and fade after thrust release; world coordinates prevent relocation during a body-frame change. Grass and character effects share the same seeded Perlin gust, direction, flutter and local clock. Wind enters pressure-dependent astronaut drag and particle drift; grounded traction preserves planted feet. Rendering uses sorted instanced billboards, translucent spherical shells, Fresnel rims and Sun highlights, at most 128 triangles and 2,048 instance bytes per view. Main and water-reflection passes share the saved pool without advancing it. These are entrained visual markers, not a thermodynamic hot-exhaust solver. Details and replay history are in `character/exhaust.md`.

#figure(grid(columns: (1fr, 1fr), gutter: 7pt,
  image("character/exhaust/images/plume.png", width: 100%),
  image("character/exhaust/images/plume-released.png", width: 100%)),
  caption: [Persistent exhaust viewed from above: powered stream (left), released jetpack with its existing tail (right). The camera exposes the plume beneath the backpack; the reduced-budget fixture omits foliage while retaining its wind field. Both images replay byte-identically.])

The actor receives terrain shadows and participates in HDR, atmosphere and water reflections. Local contact darkening helps anchor the feet; a full dynamic body shadow remains future work. CPU checks cover fixed stance contacts, joint reach, poles, mesh revision, chase clearance, 6/12 m/s movement, gravity and landing. GL captures check visible actor pixels and byte-identical gait and airborne replays; native input exercises camera switching, walking, jumping, boost and reload. These checks establish reproducibility and specific movement invariants on the tested renderer, not the naturalness of a sprint animation.

The requested Ava Turing model is not downloadable on Sketchfab. The catalog search favors Muko_Art's rigged stylized astronaut (11,718 triangles, one uploaded clip, CC BY 4.0). A logged-in download and inspection of skeleton, skin weights and retargeting remain necessary before replacing the procedural model. The shortlist and provenance are recorded in `character/sketchfab-models.md`; no external model is currently redistributed.

Grounded walking now leaves persistent grass trails. Body-local metre segments survive camera changes and planet transforms. A stackless radius-expanded BVH in an RGBA32F buffer texture selects nearby segments on both placement paths. Blades within 25 cm of the path centre lie at 8% height above the sloped walking path, extending 95% of their length along the walking direction; the effect fades smoothly to zero at 60 cm. Wind cannot lift centre blades again, while candidate roots, density, visibility and LOD remain unchanged. Airborne movement and water break path continuity, and relocation never draws a bridge between distant placements. Reload clears the history; a FIFO bound of 2,048 segments limits memory and eventually removes the oldest marks. This is geometric deformation, not a grass elasticity or recovery simulation.

#figure(
  grid(columns: (1fr, 1fr), gutter: 5pt,
    image("character/trails/images/control.png", width: 100%),
    image("character/trails/images/pressed.png", width: 100%)),
  caption: [Identical pose, terrain, foliage roots and wind phase: unpressed control (left), persistent walking trail (right). The six-metre walk records 20 segments with 977 GPU-submitted blades; its replay is byte-identical.])

Replay sidecars save the complete trail. CPU checks cover history bounds, discontinuities, invalid replay values and BVH distances at planet scale. Production-shader feedback checks fixed roots, flattened height, wind suppression, untouched surroundings, pole traversal, both geometry levels and both placement paths. Actual astronaut captures retain foliage, HDR and reflections and must replay byte-identically. Details and retained evidence are in `character/trails.md`.

The trail checkpoint combines a 52-entry full run (51 passed in 516.46 s, with RepositoryLayout waiting for the new gallery image) and targeted rechecks. Both final renderer/capture entries pass after the slope correction (122.35 s); RepositoryLayout passes after publishing the gallery. All 52 entries have passing results; this is a full run plus targeted checks, not a second clean full run. All 22 README images are regenerated and hash/fingerprint-verified, with the previous 21 PNGs unchanged. Evidence is retained under `character/trails/validation/`.

The offline checkpoint passes all 51 CTest entries in a clean 308.44 s run on GCC 12.2 / Mesa llvmpipe under Xvfb. Raw logs and compiler/executable identity are retained in `benchmarks/offline/validation/`.

= Evaluation and model boundaries

== What the evidence establishes

The exhaust/wind checkpoint passes all 56 CTest entries in a clean 675.37 s run on GCC 12.2 and Mesa llvmpipe/Xvfb with two rendering workers. Its ten new CPU cases validate emission, fading, bounded history, inertial motion and wind drag; GPU checks validate transparency, Sun gloss, depth/state preservation and 120 production-GLSL Perlin comparisons. Burn, release and retirement retain exact images and complete effect/pose replay, alongside existing gait, flight, trails and Moon checkpoints. Native wind/character input, switching and reload pass. Evidence is in `character/exhaust/validation/`.

The space-flight checkpoint passed all 53 CTest entries in 764.20 s on GCC 12.2 and Mesa llvmpipe/Xvfb with two rendering workers. The character target includes 41 CPU cases, and native input verifies WASD-only airborne ignition. Flight/Moon images and their complete poses replay exactly. Evidence is retained in `character/space-flight/validation/`.

The repository contains 56 CTest entries covering configuration and orbital invariants; terrain, camera and astronaut behavior; lighting, shadows, atmosphere and refraction on OpenGL; renderer captures; adaptive quality; and real GLFW input under Xvfb. The 22 README images are checked against their SHA-256 manifest. These checks establish specific numerical and rendered behaviors on the tested software renderer. They do not establish physical fidelity, portability to every GPU driver, or a guaranteed 20 FPS for arbitrary scenes.

The directed-flight checkpoint passed 51 of 52 entries in 814.46 s. The nine-scene atmosphere test reached its 180 s deadline after eight scenes; with a bounded 300 s allowance, its standalone rerun passed in 152.20 s on the same application binary. All 52 entries therefore have passing results through full run plus targeted recheck, not a second clean full run. The motion target contains 19 passing CPU cases, and upright and tilted flight captures replay byte-identically. Raw evidence is retained in `character/flight/validation/`.

The standing update passes eight focused character/camera/renderer checks in 133.62 s, including 22 CPU motion cases and exact standing, gait, flight and trail replay. The two standing gallery views are newly posed; the other 20 captures retain their earlier provenance, with per-image source fingerprints for the updates. This is scoped validation rather than a fresh full 52-entry run. Comparison, legacy replay and artifact records are in `character/standing/`.

The October 2 continuation checkpoint passes all 49 entries in a clean 286.14 s run on GCC 12.2 and Mesa llvmpipe/Xvfb. The frozen grass view uploads 34,664 bytes of triangle IDs; cached frames upload zero grass-buffer bytes. Culling enabled/disabled and exact replay produce identical images. The October 1 paired compute/vertex benchmark remains a historical measurement on its original EGL host; this validation does not add a hardware timing claim. Evidence is retained in `benchmarks/procedural/validation/`.

The model boundaries are deliberate. Orbits are prescribed two-body ellipses with hierarchical recoil. Terrain is a deterministic synthetic height field with bounded tessellation. Atmospheric scale heights are chosen relative to shell size; the model does not solve hydrostatic temperature profiles, cloud dynamics, weather, or multiple scattering. Refraction bends view rays and reprojects available distant imagery but keeps near opaque geometry and direct shadow rays straight. Atmospheric temperature is read from JSON rather than evolved from sunlight and orbit. These limits define what a visual comparison can support.

== Rebuilding the paper and the evidence

From the repository root, regenerate the deterministic vector figures and compile the Typst source:

```sh
python3 docs/journal/make_figures.py
typst compile --root . docs/journal/paper.typ docs/journal/paper.pdf
```

The 12 SVGs require only Python's standard library. The paper references the versioned PNGs already stored in `docs/screenshots/`. To rerun the application tests in a headless OpenGL environment, build the CMake project with testing enabled and execute `LIBGL_ALWAYS_SOFTWARE=1 xvfb-run -a ctest --test-dir build --output-on-failure`. Exact image-generation commands and checksums are in `docs/captures/generation.json`.

= Conclusion

The renderer's most useful physical separation is between the state of a world and the approximation used to draw it. A fixed terrain height field can be sampled at changing mesh densities; prescribed orbital positions can be evaluated at any time; and atmospheric extinction, in-scattering, and refractive curvature can be varied from a configured air state. The atmosphere is strongest as an interactive optical explanation of why density, path length, particle type, and visibility change a sky. Its limits are equally specific: shell-relative scale heights, RGB coefficients, single scattering, fixed reference weather, and image-based refraction prevent a predictive climate or precision optical interpretation.

= References and implementation map

R1. NASA, _Basics of Space Flight, Chapter 3: Gravity and Mechanics_, #link("https://science.nasa.gov/learn/basics-of-space-flight/chapter3-3/")[official orbit primer]. Used for the classical two-body context; the implementation details above come from `src/simulation/OrbitalSystem.h`.

R2. E. Bruneton and F. Neyret, “Precomputed Atmospheric Scattering,” _Computer Graphics Forum_ 27(4), 2008, #link("https://doi.org/10.1111/j.1467-8659.2008.01245.x")[doi:10.1111/j.1467-8659.2008.01245.x]. The project uses a smaller runtime single-scattering approximation and a limited reusable lookup.

R3. NIST Engineering Metrology Toolbox, #link("https://emtoolbox.nist.gov/wavelength/documentation.asp")[Index of Refraction of Air documentation]. Background for pressure, temperature, humidity and refractive index; this project does not claim NIST-grade refractometry.

R4. IAU 2015 resolutions, #link("https://www.iau.org/static/resolutions/IAU2015_English.pdf")[official PDF]. The rendering code uses the Resolution B2 bolometric zero-point convention for luminosity.

R5. _PlanetSimulation_ repository: implementation in `src/`, shaders in `shaders/`, checks in `tests/`, and captured images with reproducibility metadata in `docs/captures/generation.json`.

R6. NASA Glenn Research Center, #link("https://www.grc.nasa.gov/www/k-12/Numbers/Math/Mathematical_Thinking/ideal_gases_under_constant.htm")[Ideal Gases under Constant Volume, Constant Pressure, Constant Temperature, and Adiabatic Conditions]. The hydrostatic, isothermal scale-height derivation is the physical motivation for the exponential profile, not the formula used to set the renderer's shell-relative scale heights.

== Claim-to-artifact map

#table(
  columns: (1.55fr, 2.35fr, 1.8fr),
  inset: 5pt,
  stroke: 0.4pt + rgb("#dfe8eb"),
  [*Claim*], [*Primary implementation*], [*Validation*],
  [Stable terrain under LOD], [`src/rendering/geometry/Terrain.h`], [`TerrainTests`, surface capture],
  [Barycentric orbit hierarchy], [`src/simulation/OrbitalSystem.h`], [`OrbitalSystemTests`],
  [Shadowed atmosphere], [`shaders/atmosphere/atmosphere.frag`], [`TerrainShadowRenderIntegration`],
  [Temperature-controlled bend], [`src/simulation/Atmosphere.h`], [`AtmosphereTests`, GPU render test],
  [Adaptive scene scale], [`src/rendering/diagnostics/AdaptiveQuality.h`], [`AdaptiveQualityTests`, live render],
  [One-second descent], [`src/rendering/camera/CameraTransition.h`], [`CameraTransitionTests`, X11 input],
  [Planted feet and local flight], [`src/rendering/character/`], [`AstronautMotionTests`, capture and X11 input],
)
