// PlanetSimulation: physical models, numerical choices, and alternatives.
// From repository root: typst compile --root . docs/journal/paper.typ docs/journal/paper.pdf
#let navy = rgb("#17334b")
#let teal = rgb("#177f89")
#let grey = rgb("#647889")
#let pale = rgb("#f2f7f8")
#set page(paper: "a4", margin: (x: 2.0cm, y: 1.8cm), footer: context [#align(center)[#counter(page).display()]])
#set text(font: "New Computer Modern", size: 10pt)
#set par(justify: true, leading: 0.6em)
#set heading(numbering: "1.")
#show heading: set text(fill: navy)
#show figure.caption: set text(size: 8.4pt, fill: grey)

#align(center)[
  #v(0.6cm)
  #text(size: 25pt, weight: "bold", fill: navy)[Physics of a Planetary Renderer]
  #v(0.25cm)
  #text(size: 14pt, fill: teal)[Models, approximations, and alternative approaches in PlanetSimulation]
  #v(0.25cm)
  #text(size: 9.5pt, fill: grey)[Implementation study · version 0.0.1]
]
#v(0.65cm)
#block(fill: pale, radius: 7pt, inset: 14pt)[
  *Abstract.* PlanetSimulation couples terrain, prescribed orbital motion, reflected illumination, and an optically active atmosphere in an interactive renderer. This paper explains the physical ideas behind those models and the approximations that make them practical. Particular attention goes to atmospheric density, molecular and aerosol extinction, single scattering, twilight visibility, and refractive ray curvature. For each major subsystem, we compare the implemented method with a plausible alternative and state what physical behavior is retained or lost. Twelve generated vector diagrams explain the algorithms; versioned captures show actual rendering. The reported GPU benchmark comes from the project README and is qualified by its original workload and hardware. The model is intentionally limited: it does not solve climate, fluid flow, multiple atmospheric scattering, or mutual N-body gravity.
]
#v(0.3cm)
*Keywords:* real-time graphics · procedural terrain · Keplerian dynamics · atmospheric optics · adaptive rendering · reproducible engineering

= Scope and physical questions

The paper describes the current source and its reproducible images, not a claim of physical fidelity for every planet. The useful questions are causal: what determines a surface point, what gravitational model moves the bodies, what radiance reaches the eye, and which terms can be approximated without destroying the intended visual behavior? Equations are simplified descriptions of the implementation; where a coefficient is tuned for the miniature scene, that is stated explicitly. Images come from `docs/screenshots/`, with capture inputs and hashes in `docs/captures/generation.json`. Diagrams in `figures/` are explanatory schematics generated by `make_figures.py`.

The atmosphere deserves special care. A convincing sunset depends on the length and density of the optical path, not merely on a sky color. The renderer therefore keeps absorption, out-scattering, in-scattering, and geometric visibility as separate quantities. Its reference pressure and temperature are configured inputs; no weather or climate equation evolves them. Tests and controlled captures check specific invariants and regressions, but an attractive image alone cannot establish that the numerical model is physically accurate.

= Representing a planet in a camera

== From configuration to a projected sphere

A position in a planet's local mesh is transformed by a model matrix, a camera view matrix, and a projection matrix. In the project's column-vector convention,

$ x_"clip" = P V M x_"local", quad x_"ndc" = x_"clip" / w_"clip" . $

This mapping establishes which physical coordinates each calculation uses. Heights belong to the rotating planet frame; orbital positions and light directions belong to the world frame; depth and pixel reconstruction belong to the camera frame. Mixing them can make a mountain move under a stationary observer or make a shadow follow the camera. GLM supplies the matrix operations, while behavior tests check the resulting projections. @fig:transform records the data path.

#figure(image("figures/early/transforms.svg", width: 100%), caption: [The foundational transform and shading path. `P V M` follows the current shader convention; the final display transform happens after linear-light composition. Generated schematic.]) <fig:transform>

A hidden-window `--render-test` and PNG smoke test make camera framing, framebuffer readback, and image output observable in headless environments. @fig:solar is an actual capture of a compact regression scene. It is evidence of the current renderer at a fixed input state.

#figure(image("../screenshots/solar-view.png", width: 82%), caption: [Headless rendering of the compact scenario. It checks the projected positions of the bodies at a reproducible input state. Source: `docs/screenshots/solar-view.png`; provenance: `docs/captures/generation.json`.]) <fig:solar>

== A reproducible scene as an experimental unit

The JSON parser performs type and range checks before GPU resources are replaced. Scene replay stores a resolved scenario, camera, time, and quality choices next to a PNG. The image is an observation; its sidecar specifies a repeatable input state. On live reload, a new CPU scene is staged before the current one is exchanged, so an invalid or half-written file retains the last valid scene. This matters for physical comparison: changing the camera or exposure at the same time as atmospheric density would confound the result.

= Terrain as a sampled physical surface

== Procedural surface as a camera-independent function

The surface height is evaluated in a normalized planet-local radial direction $u$. A simplified form is

$ h(u) = h_"landscape"(u) + sum_i A_i f_i(u; "seed"_i, "frequency"_i, "octaves"_i). $

The implemented functions include value-noise fBm and a ridged variant. Broad continent and cliff fields determine large-scale shape; finer octaves add local detail. This is synthetic topography: it has spatial correlation and multiple length scales but no tectonics, erosion, or material transport. The seed and local coordinate frame make repeated samples of the same point deterministic. Since terrain geometry is rebuilt as the camera moves, a view-dependent height function would make the ground itself rise and fall. The current code samples `heightAt(radial)` during every LOD rebuild. @fig:terrain distinguishes the fixed field from its variable triangulation.

#figure(image("figures/early/terrain.svg", width: 100%), caption: [The height field is fixed in planet coordinates; near, middle, and far zones change only sampling density. Bars are illustrative edge densities, not an image of the actual mesh. Generated schematic.]) <fig:terrain>

The sphere begins with 20 icosahedral faces, subdivided twice into 320 stable base faces. For nearby views, each base face is assigned one of three edge-segment zones using its angular distance to the eye. A previous-zone hysteresis margin prevents repeated switching at a threshold. Steep faces can receive extra segments if the triangle budget permits. Edges shared by unequal zones are sampled once at the finer requirement, then reused on both sides; concentric interior rings fill the faces without T-junctions. The budget loop first removes optional steep refinement and then lowers less-important zones. This preserves one continuous sampled surface under a per-planet triangle ceiling.

An alternative is a cube-sphere quadtree with screen-space error bounds. It can allocate triangles more directly to projected error and support very large planets, but needs explicit seam and level-transition rules. A fixed high-resolution sphere avoids LOD transitions at the cost of drawing distant detail that cannot affect the image. Here the icosahedral base and fixed height query suit a small interactive scene where local walking must remain stable.

The sampled height feeds normals and terrain color factors as well as eye clearance. Water is a separate spherical shell, an approximation that omits tides and waves in the body's shape. The local camera follows the planet's translation and rotation through a planet-fixed frame, so the same latitude/longitude refers to the same terrain location after orbital motion or spin. Walking near a pole uses a great-circle step and parallel transport of the view basis; longitude itself becomes singular there. @fig:pole illustrates why transporting the basis in 3-D is better behaved than rebuilding it from longitude after every step.

#figure(image("figures/early/pole.svg", width: 100%), caption: [Great-circle position update and basis transport across the north pole. A longitude-derived frame can flip at the pole; a transported 3-D basis remains continuous. Generated schematic.]) <fig:pole>

#figure(image("../screenshots/surface-view.png", width: 83%), caption: [Surface-camera capture of procedurally generated terrain. Geometry derives from the stable height function while tessellation is selected for this camera. Source: current gallery.]) <fig:surface>

= Orbital motion and light transport

== Prescribed Kepler ellipses with collective mass

A body names its parent and supplies semi-major and semi-minor axes $a,b$, a mean anomaly, inclination, ascending node, and periapsis orientation. The two-body approximation gives eccentricity and period as

$ e = sqrt(1 - b^2 / a^2), quad mu = G (m_"parent" + m_"collective"), quad T = 2 pi sqrt(a^3 / mu). $

Here $a$ and $b$ are converted from the scenario's distance unit to metres before applying the SI gravitational constant; the code performs the equivalent calculation in world units. At time $t$, mean anomaly advances linearly, representing equal areas swept in equal times. A bounded bracketing solve obtains eccentric anomaly $E$ from $M = E - e sin E$, and the orbital-plane position is $(a(cos E-e), b sin E)$. Three rotations orient that ellipse in the world. The implementation uses a rationalized form near extreme periapsis to avoid cancellation. Evaluating at absolute time avoids frame-rate-dependent drift and makes pausing, replay, and speed changes deterministic.

#figure(image("figures/dynamics/kepler.svg", width: 100%), caption: [An ellipse is specified relative to a focus; a child subtree and its parent recoil around a mass-weighted center. The right panel abstracts the Earth–Moon relation; sizes and offsets are not to scale. Generated schematic.]) <fig:kepler>

Each subtree acts as a collective point mass in its parent's prescribed ellipse; children induce mass-weighted recoil of the parent. Thus an Earth–Moon pair has an internal barycenter, and the Sun moves in response to its descendants while its configured position remains the time-zero anchor. This retains the main geometric and mass-weighted effects while omitting inter-branch perturbations and tidal evolution. A symplectic N-body integrator would capture mutual perturbations and long-term exchange of energy and angular momentum, but would need initial velocities, a suitable time step, and careful treatment of close encounters. Prescribed ellipses are a good fit for deterministic scene replay, not for predicting orbital evolution.

For the `O` overlay, the application samples the complete hierarchy at 321 times for each body: ten revolutions at 32 segments per revolution. A moon's inertial trail must inherit its parent's translation rather than drawing one stationary local ellipse. @fig:trails shows that distinction.

#figure(image("figures/dynamics/orbit-trails.svg", width: 100%), caption: [Illustrative moon trail in the inertial world frame. The repeated local cycles travel with the parent; the curve is explanatory and does not plot a measured scenario trajectory. Generated schematic.]) <fig:trails>

== Light transport before atmospheric composition

Per-frame CPU lighting computes direct flux with inverse-square distance and reflected flux with geometric albedo, a diffuse-sphere phase function, and inverse-square reflector-to-receiver falloff. Sun luminosity is derived from absolute bolometric magnitude using the IAU zero point. The phase law matters: a full moon presents more of its illuminated hemisphere to the receiver than a crescent. Shaders sum direct, reflected, and indirect contributions in linear RGB before an exponential display shoulder and sRGB encoding. Summing encoded display values would break the proportional meaning of flux and exposure.

A directional orthographic depth map is made per planet from the local Sun direction. The same map constrains opaque terrain, water, and direct atmospheric scattering. Its depth test approximates geometric occlusion by terrain; it does not solve light diffraction or soft penumbrae from the full solar disk. The map is cached until local Sun direction, terrain revision, extent, or resolution changes enough to alter its result. Ray tracing each point toward the Sun would give a more direct visibility test and potentially better soft shadows, but its cost is high for every surface fragment and atmospheric sample. @fig:lighting separates the direct and reflected paths.

#figure(image("figures/dynamics/lighting.svg", width: 100%), caption: [The Sun contributes direct flux to each body, the Moon reflects a phase-dependent portion toward the planet, and terrain visibility controls direct light. The diagram is schematic; arrow widths do not encode flux.]) <fig:lighting>

#figure(grid(columns: (1fr, 1fr), gutter: 8pt,
  image("../screenshots/moonlit-night.png", width: 100%),
  image("../screenshots/moonless-night.png", width: 100%)),
  caption: [A controlled night-scene comparison from the current gallery: moonlit (left) and moonless (right). The saved replays preserve camera and lighting inputs, allowing the reflected-light term to be isolated.]) <fig:moonlight>

= Atmospheric optics: from air state to pixel radiance

== Why density is modeled as a vertical profile

In an approximately isothermal atmosphere under roughly constant gravity, hydrostatic balance and the ideal gas law produce an exponential molecular density with scale height $H approx k_B T / (m g)$ (R6). PlanetSimulation uses the same shape for molecules and a separate, usually shorter shape for aerosols:

$ rho_"m"(h) = exp(-h/H_"m"), quad rho_"a"(h) = exp(-h/H_"a") . $

This is a physically motivated shape, but the actual scale heights are set to fractions of the configured shell thickness, not calculated from local gravity and temperature. That choice keeps the visible atmosphere proportionate to a small rendered planet. Both densities taper smoothly to zero over the outer 15% of the shell so the finite numerical boundary does not appear as a hard optical edge. A hydrostatic solver with altitude-dependent temperature would produce more defensible densities, especially for a very deep atmosphere; it would also need gravity, thermal state, and boundary conditions that the current scene format does not supply.

At the reference surface, pressure and temperature scale molecular density approximately as $P/T$. Gas mixture changes the reference refractivity and Rayleigh strength. The code samples Rayleigh coefficients at three representative visible wavelengths and rescales their reference column from an 8 km Earth-like value into units of planet radii. This preserves recognizable color separation, including stronger short-wave scattering, but is not a spectral atmosphere prediction for an arbitrary small world. A spectral solver would resolve wavelength-dependent gas and aerosol properties more faithfully, then integrate to display RGB; it would require more storage and sampling per pixel.

== Extinction, scattering, and the color of the sky

Molecular scattering, aerosol scattering, and aerosol absorption enter different terms. For a path of length $s$, optical depth and direct transmittance have the Beer–Lambert form

$ tau(s) = integral_0^s beta_"ext"(l) dif l, quad T(s) = exp(-tau(s)) . $

Here $beta_"ext" = beta_"Rayleigh" rho_"m" + (beta_"aerosol-scatter" + beta_"aerosol-absorb") rho_"a"$, evaluated per RGB channel. Extinction removes light from the original scene color; only the scattering coefficients contribute light into the view. In particular, treating all dust extinction as scattering would make a dense absorbing dust layer too bright. The renderer's red-dust coefficients and droplet approximation are artistic optical parameters, while the molecular wavelength trend follows the Rayleigh idea.

The pixel combines attenuated scene radiance and light scattered into the view:

$ L_"eye" = T_"view" L_"scene" + L_"in" . $

At each view-ray sample, incoming solar radiance is reduced by transmittance along the light path. The source is multiplied by local density and a phase function: Rayleigh scattering uses a symmetric $1 + cos^2 theta$ dependence, while aerosols use a forward-peaked Henyey–Greenstein form with fixed asymmetry $g = 0.65$. The source is then attenuated along the remaining view path before reaching the eye and contributes to $L_"in"$. This is why a long low-Sun path can redden transmitted light while a nearby sky region gains blue molecular scattering. A small indirect fill term approximates light arriving from other directions; it is not a multiple-scattering solve.

The aerosol state responds to configured dust and water. The water partial pressure is compared with a temperature-dependent saturation estimate; excess vapor can become suspended liquid according to a configurable fraction. A simple droplet cross-section gives an extinction estimate from liquid mass and droplet radius. Thus cooling at fixed water input can increase cloud or mist opacity in the model. It does not simulate nucleation, droplet-size distributions, precipitation, or convective transport. A weather model could supply local pressure, temperature, humidity, and liquid water to the optical layer; the current renderer consumes one configured reference state.

Terrain and the planet also control which sample receives direct Sun light. A spherical horizon test blocks the central solar ray below the horizon; a finite solar angular radius softens the twilight transition. Away from that narrow horizon region, the terrain shadow map can block sunlight from a sample near a mountain. The finite-disk transition is an approximation rather than an integration over the Sun's actual disk, and shadow-map resolution limits the detail of mountain silhouettes. Without the terrain query, shadowed air would continue to glow as if its light path passed through a mountain.

The implementation uses bounded midpoint samples for the view integral. Within a sample it integrates constant source and extinction analytically through $(1 - exp(-beta_"ext" d s)) / beta_"ext"$, avoiding an excessive bright contribution in thick dust. A precomputed multiple-scattering atmosphere, such as the approach in R2, would describe high-order skylight and horizon brightening more faithfully. It would require larger lookup tables and careful parameterization when pressure, temperature, dust, water, or geometry change interactively. The present single-scattering calculation keeps those controls responsive and its cost bounded.

== Why refractive rays bend

The same pressure, temperature, and gas composition produce an approximate surface refractive index. At fixed pressure, cooler air is denser, increasing $n - 1$ in this model. The radial profile decreases with altitude and tapers to $n = 1$ at the shell boundary. Fermat's principle says a ray follows a path of stationary optical length; in a smoothly varying index, its direction changes according to the perpendicular component of the index gradient:

$ (d vec(d)) / (d s) = (nabla n - vec(d) (vec(d) · nabla n)) / n. $

Only the gradient perpendicular to the ray bends it; a gradient along the ray changes optical travel time but not direction. A midpoint step follows this curvature, and the radial symmetry gives a useful check: the spherical Snell quantity $n r sin theta$ should remain approximately constant. CPU tests check this invariant and ray reciprocity; GPU tests compare reprojected sky displacement with the CPU reference and check cold-versus-warm configured scenes. @fig:refraction separates ray geometry from scattered radiance.

#figure(image("figures/atmosphere/refraction.svg", width: 82%), caption: [A refractive view ray bends through denser air while solar light contributes scattered radiance. Near terrain keeps its rasterized silhouette; only visible distant imagery is reprojected. Generated schematic.]) <fig:refraction>

The renderer bends a view ray and reprojects a visible distant image pixel when that ray escapes the shell. Near terrain retains its rasterized silhouette, and direct-light shadow rays remain straight. An off-screen or hidden source cannot be reconstructed from the existing color buffer; trapped rays do not leak background light. Full curved-ray tracing through scene geometry would represent refracted terrain and solar visibility more consistently, but would require a different visibility structure and substantially more ray queries. The pressure and temperature dependence has a physical basis (R3), while the chosen constants and miniature-world scale remain a rendering model rather than precision terrestrial refractometry.

A deliberately extreme test compresses the shell to 15 m around the 1 km planet, sets pressure to 150,000 Pa and temperature to 180 K, and places the surface camera 2 m above the ground with a 15-degree field of view. The two actual renderer captures below differ only in the JSON `refraction_enabled` switch. Refraction extends the visible solar limb into sky pixels near the horizon, while the already rasterized Sun and terrain keep their silhouettes. A small pointed edge remains where terrain hides the source image; this is a limit of image reprojection rather than a prediction of solar optics. The setting illustrates the rendering model's behavior, not Earth's atmosphere. The replay sidecars in `docs/captures/replay` preserve the exact resolved scenes.

#figure(grid(columns: (1fr, 1fr), gutter: 7pt,
  image("../screenshots/refraction-extreme-on.png", width: 100%),
  image("../screenshots/refraction-extreme-off.png", width: 100%)),
  caption: [Matched full-resolution renderer captures of extreme refraction enabled (left) and disabled (right). Only the JSON bending switch changes; scattering and exposure remain active in both.]) <fig:extreme-refraction>

#figure(grid(columns: (1fr, 1fr), gutter: 7pt,
  image("../screenshots/atmosphere-day.png", width: 100%),
  image("../screenshots/atmosphere-sunset.png", width: 100%),
  image("../screenshots/atmosphere-mist.png", width: 100%),
  image("../screenshots/atmosphere-dust.png", width: 100%)),
  caption: [Current controlled atmospheric scenarios, left to right and top to bottom: standard air, sunset, condensed mist, and heavy red dust. All four are actual renderer captures from the regression gallery.]) <fig:atmosphere-gallery>

== Where the atmospheric computation is spent

For each visible pixel, the view ray needs repeated density and light-path evaluations. A reusable GPU density-column table stores the geometric integrals of molecular and aerosol density along straight light paths. Since the table stores columns rather than color, changing the gas mixture or dust coefficients can reuse the same geometry and apply new extinction coefficients. Camera motion also leaves the shell geometry unchanged. The main atmosphere field normally uses quarter resolution; a depth-aware resolve reconstructs smooth regions and reintegrates full-resolution pixels near discontinuities. Terrain, stars, and the Sun stay at full resolution. This matches the physical structure of the calculation: smooth optical fields tolerate coarse sampling, while silhouettes and depth edges do not. @fig:atmos-pipeline summarizes the pipeline.

An alternative is full-resolution ray integration for every pixel. It avoids resolve artifacts, but repeats nearly identical work across neighboring sky pixels. A larger multidimensional lookup could reduce per-pixel work further, but would be harder to update for changing aerosol and humidity states. The current split keeps the expensive geometric column reusable while leaving composition as a live control.

#figure(image("figures/atmosphere/pipeline.svg", width: 100%), caption: [Atmospheric rendering graph. A reusable density-column lookup and a reduced scattering field lower repeated work; full-resolution depth controls edge reconstruction. Generated schematic.]) <fig:atmos-pipeline>

The project's recorded Quadro M1000M benchmark at 1280×720 reported 208 ms mean frame time for the original full-field method, 138 ms with the column lookup, and 26 ms with reduced fields and shared ray calculations. These were 90-frame measurements of one surface scene with Debug CPU builds, recorded in the README; @fig:perf reproduces them rather than claiming a new experiment. The approximately eightfold change is specific to that workload and GPU. A separate RelWithDebInfo run reported 28.5 ms. A headless software-rendered capture is not comparable to this hardware benchmark.

#figure(image("figures/atmosphere/performance.svg", width: 100%), caption: [Reported mean frame times from `README.md`, Quadro M1000M, 1280×720, 90 frames. These bars visualize previously reported measurements, not a new benchmark.]) <fig:perf>

A profiler now records CPU stage times and asynchronous GPU timestamp results without blocking for each query. CPU frame time, GPU pass time, and swap/presentation delay answer different questions; adding CPU and GPU times would double-count overlap. A completed HDR scene may be reused if camera, time, viewport, geometry, and pending-terrain state match. The HUD remains separately drawn so input can reveal or hide it immediately.

= Visibility, exposure, and interactive constraints

== Diagnostics, dependency boundaries and adaptive quality

The `I`/Tab panel reports timings and optional Linux NVIDIA NVML utilization. Utilization is sampled off the render thread and is device-wide, while GPU pass milliseconds belong to this application's measured passes. Software rendering and ambiguous GPU matching show `N/A`; a fake driver library tests the ABI path without claiming validation on NVIDIA hardware. @fig:overlay is a real captured panel.

#figure(image("../screenshots/performance-overlay.png", width: 83%), caption: [Actual current performance overlay under Xvfb/Mesa llvmpipe. The white-bordered black panel reports FPS, frame time, GPU pass time, and utilization availability; its numbers are capture-environment observations.]) <fig:overlay>

A best-effort 20 FPS quality target uses a smoothed frame estimate $m_t = 0.85 m_(t-1) + 0.15 f_t$ to select one of six scene-resolution scales, from 100% down to 25%. After a 1.5-second cooldown, sustained times above 55 ms lower resolution; times below 32 ms permit recovery. Only moving interactive scenes feed the controller. A graphics-memory estimate can cap the initial scale, reserving most reported memory for other uses; fixed-resolution captures remain deterministic. The HUD stays at native window resolution. @fig:adaptive shows the control law, not a measured response trace. This is a rendering control, not a change to the atmosphere's physical parameters. Its lower resolution may still lose thin clouds or distant silhouettes; a strict 20 FPS guarantee is impossible once the minimum scale is reached or scene cost is unrelated to pixel count.

#figure(image("figures/interaction/adaptive.svg", width: 100%), caption: [Actual controller thresholds and discrete scene scales; bar heights are relative scale, not measured frame rates. Generated schematic.]) <fig:adaptive>

== Visibility must follow the light path

The same visibility principle applies to air and water. A mountain blocks direct sunlight from nearby air, so the direct in-scattering term uses the planet's terrain depth map. The finite solar disk's twilight region remains, as does the approximate indirect fill. For water, a valid bright sample in the reflection image does not prove that a water point is lit: that point may lie on the night side or behind terrain. The direct reflection term therefore requires positive local Sun incidence and terrain visibility. Indirect water radiance remains. @fig:ocean illustrates the distinction. The gallery's terrain-shadow and twilight cases are controlled visual regressions.

#figure(image("figures/dynamics/ocean.svg", width: 100%), caption: [A reflected bright sample can exist in image space even when the water point lies on the night side. Local incidence and shadow-map visibility gate the direct reflection term. Generated schematic.]) <fig:ocean>

#figure(grid(columns: (1fr, 1fr), gutter: 8pt,
  image("../screenshots/terrain-shadows.png", width: 100%),
  image("../screenshots/twilight.png", width: 100%)),
  caption: [Actual current regression captures for terrain shadow visibility (left) and near-horizon twilight (right). Their fixtures and generation commands are recorded with the gallery.]) <fig:shadow-twilight>

== Interpreting motion from the camera

Ten-revolution predictive trails and body cards help distinguish local orbits from inertial paths. The path color averages terrain vertex RGB factors multiplied by the body's configured base tint; labels report name, parent, axes, eccentricity, period, radius, and mass. Sampling the entire orbital system, rather than each child's local ellipse alone, is necessary for moving-parent trails. The overlay is toggled by `O` and hidden in planet and surface cameras; real X11 input tests verify both behaviors.

Orbit-to-surface entry is a one-second wall-clock transition. The starting pose is the last actually rendered view, avoiding a first-frame jump after the key event. An eased parameter $q(u)=3u^2-2u^3$ drives spherical interpolation of the planet-relative radial direction, logarithmic interpolation of radius, quaternion interpolation of orientation, and field-of-view interpolation. Intermediate positions are clamped above sampled terrain and water. The target is resampled while the planet moves, so the transition ends at the current surface pose. This is a camera path, not a physically accelerated descent; a dynamics-based flight model would require forces, velocities, and collision response. @fig:transition shows the path and ease curve.

#figure(image("figures/interaction/transition.svg", width: 100%), caption: [Orbit-to-surface descent. The curve shows the implemented smoothstep parameter; the spatial path is schematic because the actual start, target, and terrain vary by scene.]) <fig:transition>

= Evaluation and model boundaries

== What the evidence establishes

The repository contains 39 CTest entries covering configuration and orbital invariants; terrain and camera behavior; lighting, shadows, atmosphere and refraction on OpenGL; renderer captures; adaptive quality; and real GLFW input under Xvfb. The 12 README images are checked against their SHA-256 manifest. These checks establish specific numerical and rendered behaviors on the tested software renderer. They do not establish physical fidelity, portability to every GPU driver, or a guaranteed 20 FPS for arbitrary scenes.

The model boundaries are deliberate. Orbits are prescribed two-body ellipses with hierarchical recoil. Terrain is a deterministic synthetic height field with bounded tessellation. Atmospheric scale heights are chosen relative to shell size; the model does not solve hydrostatic temperature profiles, cloud dynamics, weather, or multiple scattering. Refraction bends view rays and reprojects available distant imagery but keeps near opaque geometry and direct shadow rays straight. Atmospheric temperature is read from JSON rather than evolved from sunlight and orbit. These limits define what a visual comparison can support.

== Rebuilding the paper and the evidence

From the repository root, regenerate the deterministic vector figures and compile the Typst source:

```sh
python3 docs/journal/make_figures.py
typst compile --root . docs/journal/paper.typ docs/journal/paper.pdf
```

The 12 SVGs require only Python's standard library. The paper references the versioned PNGs already stored in `docs/screenshots/`. To rerun the application tests in a headless OpenGL environment, build the CMake project with testing enabled and execute `LIBGL_ALWAYS_SOFTWARE=1 xvfb-run -a ctest --test-dir build --output-on-failure`. Exact image-generation commands and checksums are in `docs/captures/generation.json`.

= Conclusion

The renderer's most useful physical separation is between the state of a world and the approximation used to draw it. A fixed terrain height field can be sampled at changing mesh densities; prescribed orbital positions can be evaluated at any time; and atmospheric extinction, in-scattering, and refractive curvature can be varied from a configured air state. The atmosphere is strongest as an interactive optical explanation of why density, path length, particle type, and visibility change a sky. Its limits are equally specific: shell-relative scale heights, RGB coefficients, single scattering, fixed reference weather, and image-based refraction prevent a predictive climate or precision optical interpretation.

= References and implementation map

R1. NASA, _Basics of Space Flight, Chapter 3: Gravity and Mechanics_, #link("https://science.nasa.gov/learn/basics-of-space-flight/chapter3-3/")[official orbit primer]. Used for the classical two-body context; the implementation details above come from `src/simulation/OrbitalSystem.h`.

R2. E. Bruneton and F. Neyret, “Precomputed Atmospheric Scattering,” _Computer Graphics Forum_ 27(4), 2008, #link("https://doi.org/10.1111/j.1467-8659.2008.01245.x")[doi:10.1111/j.1467-8659.2008.01245.x]. The project uses a smaller runtime single-scattering approximation and a limited reusable lookup.

R3. NIST Engineering Metrology Toolbox, #link("https://emtoolbox.nist.gov/wavelength/documentation.asp")[Index of Refraction of Air documentation]. Background for pressure, temperature, humidity and refractive index; this project does not claim NIST-grade refractometry.

R4. IAU 2015 resolutions, #link("https://www.iau.org/static/resolutions/IAU2015_English.pdf")[official PDF]. The rendering code uses the Resolution B2 bolometric zero-point convention for luminosity.

R5. _PlanetSimulation_ repository: implementation in `src/`, shaders in `shaders/`, checks in `tests/`, and captured images with reproducibility metadata in `docs/captures/generation.json`.

R6. NASA Glenn Research Center, #link("https://www.grc.nasa.gov/www/k-12/Numbers/Math/Mathematical_Thinking/ideal_gases_under_constant.htm")[Ideal Gases under Constant Volume, Constant Pressure, Constant Temperature, and Adiabatic Conditions]. The hydrostatic, isothermal scale-height derivation is the physical motivation for the exponential profile, not the formula used to set the renderer's shell-relative scale heights.

== Claim-to-artifact map

#table(
  columns: (1.55fr, 2.35fr, 1.8fr),
  inset: 5pt,
  stroke: 0.4pt + rgb("#dfe8eb"),
  [*Claim*], [*Primary implementation*], [*Validation*],
  [Stable terrain under LOD], [`src/rendering/geometry/Terrain.h`], [`TerrainTests`, surface capture],
  [Barycentric orbit hierarchy], [`src/simulation/OrbitalSystem.h`], [`OrbitalSystemTests`],
  [Shadowed atmosphere], [`shaders/atmosphere/atmosphere.frag`], [`TerrainShadowRenderIntegration`],
  [Temperature-controlled bend], [`src/simulation/Atmosphere.h`], [`AtmosphereTests`, GPU render test],
  [Adaptive scene scale], [`src/rendering/diagnostics/AdaptiveQuality.h`], [`AdaptiveQualityTests`, live render],
  [One-second descent], [`src/rendering/camera/CameraTransition.h`], [`CameraTransitionTests`, X11 input],
)
